export const auth=async(req,res,next)=>{
    try{

    }catch(err){
        res.json({message:err});
    }
}